public without sharing class AccountHandler implements TriggerInterface {

    
    public void bulkBefore() {        
    }

    public void bulkAfter() {
    }

    public void beforeInsert(SObject sObjectInstance) {   
    }

    public void beforeUpdate(SObject oldSObjectInstance, SObject newSObjectInstance) {       
    }

    public void beforeDelete(SObject sObjectInstance) {       
    }

    public void afterInsert(SObject sObjectInstance) {
    }

    public void afterUpdate(SObject oldSObjectInstance, SObject newSObjectInstance) {
    }

    public void afterDelete(SObject sObjectInstance){        
    }
 
    public void afterUndelete(SObject sObjectInstance){        
    }

    public void andFinally(){
    }
}