@isTest
private class AchworksComTest {

    private static testMethod void AchworksComTest() {
    	
    	AchworksCom.GetACHReturnsHistRC_element returnHistElement = new AchworksCom.GetACHReturnsHistRC_element();
    	AchworksCom.GetResultFile_element resutlFileElement = new AchworksCom.GetResultFile_element();
    	AchworksCom.ArrayOfACHReturnRecord returnRecord = new AchworksCom.ArrayOfACHReturnRecord();
    	AchworksCom.SendACHTransBatchResponse_element responseElement = new AchworksCom.SendACHTransBatchResponse_element();
    	AchworksCom.TransResult transResult = new AchworksCom.TransResult();
    	AchworksCom.ErrorFile errorFile = new AchworksCom.ErrorFile();
    	AchworksCom.ViewACHTransBatch_element transBatch_element = new AchworksCom.ViewACHTransBatch_element();
    	AchworksCom.GetACHReturnsHistRCResponse_element responseHistElement = new AchworksCom.GetACHReturnsHistRCResponse_element();
    	AchworksCom.ACHTransRecord transRecord = new AchworksCom.ACHTransRecord();
    	AchworksCom.ACHReturns achReturns = new AchworksCom.ACHReturns();
    	AchworksCom.GetACHReturns_element returnsElement = new AchworksCom.GetACHReturns_element();
    	AchworksCom.ArrayOfIATACHTransRecord arrayRecords = new AchworksCom.ArrayOfIATACHTransRecord();
    	AchworksCom.GetResultFileResponse_element resultFileResponseElement = new AchworksCom.GetResultFileResponse_element();
    	
    	AchworksCom.SendACHTransBatchBinResponse_element binResponse = new AchworksCom.SendACHTransBatchBinResponse_element();
    	AchworksCom.ArrayOfString arrayOfString = new AchworksCom.ArrayOfString();
    	AchworksCom.SendIATACHTransBatchResponse_element transBatchResponse = new AchworksCom.SendIATACHTransBatchResponse_element();
    	AchworksCom.ResultFile resultFile = new AchworksCom.ResultFile();
    	AchworksCom.SendACHTransResponse_element sendACHTransResponse_element = new AchworksCom.SendACHTransResponse_element();
    	AchworksCom.ViewACHTransBatchResponse_element viewACHTransBatchResponse_element = new AchworksCom.ViewACHTransBatchResponse_element();
    	AchworksCom.GetACHReturnsHistResponse_element getACHReturnsHistResponse_element = new AchworksCom.GetACHReturnsHistResponse_element();
    	AchworksCom.ArrayOfTransResult arrayOfTransResult = new AchworksCom.ArrayOfTransResult();
    	AchworksCom.ArrayOfErrorRecord arrayOfErrorRecord = new AchworksCom.ArrayOfErrorRecord();
    	AchworksCom.IATACHTransRecord iATACHTransRecord = new AchworksCom.IATACHTransRecord();
    	AchworksCom.GetACHReturnsRC_element getACHReturnsRC_element = new AchworksCom.GetACHReturnsRC_element();
    	AchworksCom.GetACHReturnsHistBinResponse_element getACHReturnsHistBinResponse_element = new AchworksCom.GetACHReturnsHistBinResponse_element();
    	AchworksCom.SendACHTrans_element sendACHTrans_element = new AchworksCom.SendACHTrans_element();
    	AchworksCom.GetACHReturnsHistBin_element getACHReturnsHistBin_element = new AchworksCom.GetACHReturnsHistBin_element();
    	
    	AchworksCom.ConnectionCheckResponse_element connectionCheckResponse_element = new AchworksCom.ConnectionCheckResponse_element();
    	AchworksCom.SendIATACHTransBatch_element sendIATACHTransBatch_element = new AchworksCom.SendIATACHTransBatch_element();
    	AchworksCom.GetACHReturnsHist_element getACHReturnsHist_element = new AchworksCom.GetACHReturnsHist_element();
    	AchworksCom.CheckCompanyStatusResponse_element checkCompanyStatusResponse_element = new AchworksCom.CheckCompanyStatusResponse_element();
    	AchworksCom.CheckCompanyStatus_element checkCompanyStatus_element = new AchworksCom.CheckCompanyStatus_element();
    	AchworksCom.GetACHReturnsBin_element getACHReturnsBin_element = new AchworksCom.GetACHReturnsBin_element();
    	AchworksCom.DeleteACHTransBatchResponse_element deleteACHTransBatchResponse_element = new AchworksCom.DeleteACHTransBatchResponse_element();
    	AchworksCom.ErrorRecord errorRecord = new AchworksCom.ErrorRecord();
    	AchworksCom.ACHReturnRecord aCHReturnRecord = new AchworksCom.ACHReturnRecord();
    	AchworksCom.GetACHReturnsRCResponse_element getACHReturnsRCResponse_element = new AchworksCom.GetACHReturnsRCResponse_element();
    	AchworksCom.GetErrorFileResponse_element getErrorFileResponse_element = new AchworksCom.GetErrorFileResponse_element();
    	
    }
}