<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <customApplicationComponents>
        <alignment>right</alignment>
        <customApplicationComponent>Console.BuiltInComponent.mostRecentlyUsed</customApplicationComponent>
    </customApplicationComponents>
    <defaultLandingTab>standard-home</defaultLandingTab>
    <detailPageRefreshMethod>none</detailPageRefreshMethod>
    <isServiceCloudConsole>true</isServiceCloudConsole>
    <label>M Console</label>
    <listPlacement>
        <location>left</location>
        <units>percent</units>
        <width>20</width>
    </listPlacement>
    <listRefreshMethod>none</listRefreshMethod>
    <tab>standard-Lead</tab>
    <tab>standard-Account</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Case</tab>
    <tab>Syndication__c</tab>
    <tab>ISOs</tab>
    <tab>Banks</tab>
    <tab>Admin_Page</tab>
    <workspaceMappings>
        <mapping>
            <tab>standard-Opportunity</tab>
        </mapping>
        <mapping>
            <fieldName>AccountId</fieldName>
            <tab>standard-Case</tab>
        </mapping>
        <mapping>
            <tab>ISOs</tab>
        </mapping>
        <mapping>
            <tab>Admin_Page</tab>
        </mapping>
        <mapping>
            <tab>Banks</tab>
        </mapping>
        <mapping>
            <tab>standard-Lead</tab>
        </mapping>
        <mapping>
            <tab>standard-Account</tab>
        </mapping>
        <mapping>
            <tab>Syndication__c</tab>
        </mapping>
    </workspaceMappings>
</CustomApplication>
