public class DynamicComponentExample {
    public DynamicComponentExample(ApexPages.StandardController con) { }
    public Component.Apex.SectionHeader getHeaderWithDueDateCheck() {
        
        
          
       
        return null;
        
        
       /* Component.Apex.SectionHeader sectionHeader = new Component.Apex.SectionHeader();
        
            sectionHeader.title = 'Form Submission';
            return sectionHeader;*/
       
    }
}